### ISSUE TITLE
Add Documentation About the 'events' Configuration Option

### ISSUE THREAD

**Issue by aloisbarreras** [astronomer-integrations/analytics.js-integration-outbrain#3]
In the readme, just give a brief description of how OutBrain works and tie it in with how that fits in to the 'events' configuration option.

**Comment by aloisbarreras** [comment]
@RyanPnayR list out the individual config options with a header and short description like we do in the other repos. I removed the paragraph you wrote for the config to get this release pushed, but still come back and fix this.

**Comment by ryw** [comment]
@paolaperaza not sure exactly what Alois + Ryan were talking about here, but this doc linked from our nav is broken https://docs.astronomer.io/v2/clickstream/destinations/outbrain.html

**Comment by paolaperaza** [comment]
@ryw ah, I'll get that link fixed and look into our OutBrain integration today/add to the doc.

**Comment by paolaperaza** [comment]
Link fixed. Will beef up the doc, but there aren't many configuration options on our connection right now - just events and one `AdvertiserID`. 

I'll keep looking into it and update/close this accordingly.

**Comment by paolaperaza** [comment]
@ryw updated the screenshot to fit our new UI and made some copy changes. There is an example "event" in there - are we good to close this?

**Comment by ryw** [comment]
absolutely - closing
